### ISSUE TITLE
Chronogram

### ISSUE THREAD

**Issue by Pabloo22** [Pabloo22/gnn_scheduler#3]
Full project deadline: **May 15th**
### Phase 1: Literature Review
Phase deadline: **February 15th**
See Issue #4 
### Phase 2: Environment and Dataset creation
Phase deadline: **March 15th**
- [ ] Create a Dataset with solved instances.
- [ ] Create a Gymnasium Environment.
### Phase 3: Neural Architecture Search and Pre-Training
Phase deadline: **April 15th**
- [ ] Create experiments for predicting similarity between operations based only on job and machine assignment.
### Phase 4: Final experiments solving the JSP
